### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by stephenfeather** [pouriaa/bitbucket-to-github#2]
May want to make sure that all promises are caught.

**Comment by jburnett** [comment]
I had the same problem today.
`(node:1772341) UnhandledPromiseRejectionWarning: StatusCodeError: 401 - undefined
    at new StatusCodeError (/home/jb/src/github.com/pouriaa/bitbucket-to-github/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/home/jb/src/github.com/pouriaa/bitbucket-to-github/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/home/jb/src/github.com/pouriaa/bitbucket-to-github/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/home/jb/src/github.com/pouriaa/bitbucket-to-github/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (/home/jb/src/github.com/pouriaa/bitbucket-to-github/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:198:13)
    at IncomingMessage.<anonymous> (/home/jb/src/github.com/pouriaa/bitbucket-to-github/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:1772341) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1772341) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

**Comment by pouriaa** [comment]
@jburnett make sure that you have the right tokens to auth into your Github and Bitbucket accounts
